language: node_js
dist: trusty
cache:
  directories:
    - node_modules
node_js:
  - "10"
install:
  - npm install hexo-cli -g
  - hexo init blog
  - cd blog
  - cd themes
  - rm -rf /landscrape
  - git clone https://github.com/aiokr/hexo-theme-type.git landscrape
  - cd ../
script: 
  - hexo g
after_script: 
  - cd ./public
  - git init
  - git config --global push.default matching
  - git config --global user.email "${GitHubEMail}"
  - git config --global user.name "aiokr"
  - git add --all .
  - git commit -m "Auto Builder of ${GitHubUser}'s dev"
  - git push --force "https://${GitHubKEY}@github.com/${GitHubUser}/type-live-Pages.git" master
  - deploy.sh > /dev/null
  - npm run clean