# basic
favicon: 
avatar: 
drawer_header: 

# Nav link
nav:
  首页: 
    link: /
    color: '#2196F3'
    icon: home
  搜索: 
    link: /search.html
    icon: search
    color: '#2196F3'
  归档: 
    link: /archives/
    icon:   move_to_inbox
    color: '#2196F3'
  关于: 
    link: /about.html
    icon: person
    color: '#2196F3'

# footer
# about
start_time: 
footer: 
# info
count: false
busuanzi: false
# ICP
icp: 
# CDN
# Use upyun
cdn: 
  use: upyun
  upyun: 
    src: 

# Post
default_post_title: Untitled
auto_excerpt:
  length: 120

# Comment
# Use gitment | valine | disqus | disqusjs
comment:
  use:
  gitment:
    owner:
    repo:
    client_id:
    client_secret:
  valine:
    appid:
    appkey:
  disqus:
    src: 
    # such as: https://xxx.disqus.com/embed.js
  disqusjs:
    shortname: 
    siteName: 
    api: 
    apikey: 
    admin: 
    adminLabel: 

# Random Pictures
random_pics: 24

# Google Analytics
google_analytics: UA-XXXXXXXXX-A